---
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: cstor-pool-demo
  annotations:
    cas.openebs.io/create-pool-template: cstor-pool-create-default-0.7.0
    cas.openebs.io/delete-pool-template: cstor-pool-delete-default-0.7.0
spec:
  name: cstor-pool-demo
  type: sparse
  maxPools: 3
  poolSpec:
    poolType: striped
    cacheFile: /tmp/pool1.cache
    overProvisioning: false
  disks:
    diskList:
      - disk-2709a1cba9cea9407b92bc1f7d1a1bde
      - disk-427145375f85e8a488eeb8bbfae45118
      - disk-c9273728d4018268ffac2df33520e4ca
