kind: Namespace
apiVersion: v1
metadata:
  name: percona
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: percona-pvc
  namespace: percona
spec:
  storageClassName: openebs-cstor-default-0.7.0
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G

