apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesJson6902:
- target:
    group: networking.k8s.io
    version: v1beta1 
    kind: Ingress
    name: maya-auth-ingress 
  path: ingress_patch.json
resources:
- ingress.yaml
