---
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: pool1
spec:
  name: pool1
  # format: "value"
  # mountpoint: "value"
  # path: "value"
  type: openebs-cstor
  maxPools: 3
