---
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: pool1
  annotations:
    cas.openebs.io/create-template: cast-standard-cstorpool-0.6.0
spec:
  name: pool1
  type: openebs-cstor
  maxPools: "1"
  poolSpec:
    poolType: striped
    cacheFile: /tmp/pool1.cache
    overProvisioning: false
  disks:
    diskList:
      - disk-b017994ee0218160deb8586947eb85d6
      - disk-b536b046bded6a4d4038223cec5509fd
      - disk-a85d9ceee7f182d03fded326703d3d8f
      - disk-66a4d7bb2f5e7b9b8dc191b6e70e757f
      - disk-160f8450ad7e7930821aa9a2774cb8c3
      - disk-16f1c51e0d22b5404d012ecb9a61f465


