---
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: pool1
  # Cluster Scoped? Do we need Namespace?
  # This way of setting namespace will get first priority.
  # namespace: default
  annotations:
    # This the CASTemplate which will be used to provision cstor pool.
    cas.openebs.io/create-template: cast-standard-cstorpool-0.6.0
  # labels:
    # Cluster Scoped? Do we need Namespace?
    # This manner of setting namespace gets the second priority.
    # namespace: default

spec:
  name: pool1
  # format: "value"
  # mountpoint: "value"
  # path: "value"
  type: openebs-cstor
  nodeSelector: ["node1", "node2", "node3"]
  maxPools: "3"
  capacity: "5G"
  poolSpec:
    # poolName: cstorpool1
    poolType: striped
    # cacheFile: "value"
  # Do we need to provide disk list in spc yaml? I guess no.
  # disks:
   # diskList: ["disk1", "disk2", "disk3"]
