---
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: pool1
  annotations:
    # This the CASTemplate which will be used to provision cstor pool.
    cas.openebs.io/create-template: cast-standard-cstorpool-0.6.0
spec:
  name: pool1
  # format: "value"
  # mountpoint: "value"
  # path: "value"
  type: openebs-cstor
  nodeSelector: ["node1", "node2", "node3"]
  maxPools: "3"
  capacity: "5G"
  poolSpec:
    poolType: striped
    # cacheFile: "value"
