apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    cas.openebs.io/config: |
      - name: CStorPoolCluster
        value: "cspc-mirror"
      - name: ReplicaCount
        value: "1"
    openebs.io/cas-type: cstor
  name: openebs-cstor-mirror
provisioner: openebs.io/provisioner-iscsi
