apiVersion: v1
kind: ConfigMap
metadata:
  name: cstor-pool-create-put-cr-0.6.0
  namespace: default
data:
  meta: |
    runNamespace: {{ .Volume.runNamespace }}
    apiVersion: openebs.io/v1alpha1
    kind: CStorPool
    action: put
    id: createputcstorpool
    repeatWith:
      resources:
        {{- range $k, $v := .ListItems.cstorNodePoolList.nodes}}
        - {{ $k }}
        {{- end }}
  post: |
    {{- jsonpath .JsonResult `{.metadata.name}` | trim | saveAs "createputcstorpool.objectName" .TaskResult | noop -}}
    {{- $nodeUidMap := jsonpath .JsonResult `pkey=nodesUid {.metadata.labels.kubernetes\.io/hostname}={.metadata.uid};` | trim | default "" | splitList ";" -}}
    {{- $nodeUidMap | asKeyMap "cstorNodeUidList" .ListItems | noop -}}
  task: |
    apiVersion: openebs.io/v1alpha1
    kind: CStorPool
    metadata:
      name: {{.CstorPool.owner}}-{{ .ListItems.currentRepeatResource}}
      labels:
        cas.openebs.io/storage-pool-claim: {{.CstorPool.spc}}
        kubernetes.io/hostname: {{ .ListItems.currentRepeatResource }}
    spec:
      disks:
        diskList: {{ pluck .ListItems.currentRepeatResource .ListItems.cstorNodePoolList.nodes }}
      poolSpec:
        poolType: {{.CstorPool.poolType}}
