---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-cstor-disk-auto
  annotations:
    cas.openebs.io/create-volume-template: cstor-volume-create-default-0.7.0
    cas.openebs.io/delete-volume-template: cstor-volume-delete-default-0.7.0
    cas.openebs.io/read-volume-template: cstor-volume-read-default-0.7.0
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "disk-claim-auto"
      #- name: TargetResourceLimits
      #  value: |-
      #      memory: 1Gi
      #      cpu: 200m
      #- name: AuxResourceLimits
      #  value: |-
      #      memory: 0.5Gi
      #      cpu: 50m
provisioner: openebs.io/provisioner-iscsi
---
kind: Namespace
apiVersion: v1
metadata:
  name: percona
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: percona-pvc
  namespace: percona
spec:
  storageClassName: openebs-cstor-disk-auto
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G

