kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cstor-stripe-claim
spec:
  storageClassName: openebs-cstor-stripe
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4G

