apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
vars:
  - name: SERVICE_BALANCE_TYPE
    objref:
      kind: Service
      name: cspc-injector-service 
      apiVersion: v1
    fieldref:
      fieldpath: spec.type
resources:
- cspc-operator.yaml
- svc.yaml
- service-account.yaml
- crd.yaml
