apiVersion: openebs.io/v1alpha1
kind: CASTemplate
metadata:
  name: cast-standard-cstorpool-0.6.0
spec:
  defaultConfig:
  - name: capacity
    value: "3G"
  - name: maxPool
    value: "3"
  run:
    taskNamespace: default
    tasks:
    - task: cstor-pool-create-put-cr-0.6.0
      id: vcstorpool
