apiVersion: v1
kind: ConfigMap
metadata:
  name: cstor-pool-create-put-cr-0.6.0
  namespace: default
data:
  meta: |
    id: createputcstorpool
    runNamespace: {{ .Volume.runNamespace }}
    apiVersion: openebs.io/v1alpha1
    kind: CStorPool
    action: put
  post: |
    {{- jsonpath .JsonResult "{.metadata.name}" | trim | saveAs "createputcstorpool.objectName" .TaskResult | noop -}}
  task: |
    apiVersion: openebs.io/v1alpha1
    kind: CStorPool
    metadata:
      name: {{.CstorPool.owner}}
      labels:
        cas.openebs.io/storage-pool-claim: {{.CstorPool.spc}}
        kubernetes.io/hostname: {{.CstorPool.hostName}}
    spec:
      disks:
        diskList: ["disk1"]
      poolSpec:
        poolType: {{.CstorPool.poolType}}
