---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spc-disk-list-0.6.0
  namespace: default
data:
  meta: |
    {{- $disklist := .Cstor.diskList | default "" | splitList ", " -}}
    id: spcdisklist
    repeatWith: 
      kind: namespace
      resources:
      {{- range $index, $disk := $disklist }} 
      - {{ $disk }}
      {{- end }}
    apiVersion: openebs.io/v1alpha1
    kind: Disks
    objectName: {{ $disk }}
    action: get
  post: |
    {{- $nodeDiskMap := jsonpath .JsonResult `{range .items[*]}pkey=nodeDisk {@.metadata.labels.kubernetes\.io/hostname}={@.metadata.name};{end}` | trim | default "" | splitList ";" -}}
    {{- $nodeDiskMap | asKeyMap "nodeList" .ListItems | noop -}}
---
